version: '3'

services:
  legrid:
    container_name: ${USER:-safierinx}_legrid
    build: ./legrid
    ports:
      - "4000:4000"
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - LEGRID_GRID_WIDTH=25
      - LEGRID_GRID_HEIGHT=24
    volumes:
      - ./legrid:/app
    command: mix phx.server
    networks:
      - default

networks:
  default:
    name: ${USER:-safierinx}_network
    external: true 