version: '3'

services:
  legrid:
    container_name: ${USER}_legrid
    build:
      context: ./legrid
    ports:
      - "4000:4000"
    environment:
      - MIX_ENV=dev
      - PHX_HOST=0.0.0.0
      - PORT=4000
      - GRID_WIDTH=25
      - GRID_HEIGHT=24
    volumes:
      - ./legrid:/app
      - /app/deps
      - /app/_build
    restart: unless-stopped

networks:
  default:
    name: ${USER}_network
    external: true 