# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

# HTTP Configuration for proxy
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.18.0.0/16    # Docker network subnet
    - 127.0.0.1        # Localhost

# Authentication providers
homeassistant:
  auth_providers:
    - type: homeassistant

# Frontend and theme configuration
frontend:
  themes: !include_dir_merge_named themes

# MQTT Sensors configuration
mqtt:
  sensor:
    # Your existing air quality sensors
    - name: "Air Quality Index"
      state_topic: "sensors/ens160/aqi"
      device_class: aqi
      state_class: measurement
      icon: mdi:air-filter
      suggested_display_precision: 0
      value_template: "{{ value | float }}"

    - name: "Total Volatile Organic Compounds"
      state_topic: "sensors/ens160/tvoc"
      unit_of_measurement: "µg/m³"
      device_class: volatile_organic_compounds
      state_class: measurement
      icon: mdi:molecule
      suggested_display_precision: 1
      value_template: "{{ (value | float * 3.767) | round(1) }}"

    - name: "CO2 Equivalent"
      state_topic: "sensors/ens160/eco2"
      unit_of_measurement: "ppm"
      device_class: carbon_dioxide
      state_class: measurement
      icon: mdi:molecule-co2
      suggested_display_precision: 0
      value_template: "{{ value | float }}"

    # LED Grid Sensors (Updated)
    - name: "LED FPS"
      state_topic: "led/status/performance/fps"
      unit_of_measurement: "FPS"
      icon: mdi:speedometer

    - name: "LED Frame Time"
      state_topic: "led/status/performance/frame_time"
      unit_of_measurement: "ms"
      icon: mdi:timer

    - name: "Pattern Server Status"
      state_topic: "led/status/pattern_server"
      icon: mdi:server

    - name: "LED Controller Status"
      state_topic: "led/status/led_controller"
      icon: mdi:led-strip

    - name: "Last Reset Time"
      state_topic: "led/status/hardware/last_reset"
      device_class: "timestamp"
      icon: mdi:clock-outline

  button:
    - name: Reset LEDs
      command_topic: "led/command/reset"
      payload_press: "RESET"
      icon: mdi:restart

    - name: Clear LEDs
      command_topic: "led/command/clear"
      payload_press: "CLEAR"
      icon: mdi:led-off

    - name: Stop Pattern
      command_topic: "led/command/stop"
      payload_press: "STOP"
      icon: mdi:stop

  switch:
    - name: LED Power
      state_topic: "led/status/hardware/power"
      command_topic: "led/command/power"
      payload_on: "ON"
      payload_off: "OFF"
      state_on: "ON"
      state_off: "OFF"
      icon: mdi:power

# LED Grid Configuration (Updated)
input_select:
  led_grid_pattern:
    name: LED Pattern
    options:
      - "Default"  # Default option
    icon: mdi:led-strip-variant

  pattern_variation:
    name: Pattern Variation
    options:
      - "Default"  # Default option
    icon: mdi:palette-advanced

  pattern_color_mode:
    name: Color Mode
    options:
      - "Default"  # Default option
    icon: mdi:palette

input_number:
  pattern_speed:
    name: Pattern Speed
    min: 0.1
    max: 5.0
    step: 0.1
    mode: slider
    icon: mdi:speedometer

  pattern_scale:
    name: Pattern Scale
    min: 0.1
    max: 3.0
    step: 0.1
    mode: slider
    icon: mdi:scale

  pattern_intensity:
    name: Pattern Intensity
    min: 0.0
    max: 1.0
    step: 0.05
    mode: slider
    icon: mdi:brightness-percent

  led_brightness:
    name: LED Brightness
    min: 0.0
    max: 1.0
    step: 0.01
    mode: slider
    icon: mdi:brightness-6

# Keep your existing includes
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml