defmodule Legrid.Controller.Frame do
  @moduledoc """
  Represents a frame of LED state that can be rendered.

  This struct is used to represent a single frame of LED state in the system.
  Frames are generated by pattern generators and sent to controllers.
  """

  defstruct [:pixels, :timestamp, :metadata, :id]

  @doc """
  Creates a new frame with the given pixels and options.

  Options:
  - :metadata - Additional metadata to include with the frame
  """
  def new(pixels, opts \\ []) do
    metadata = Keyword.get(opts, :metadata, %{})

    %__MODULE__{
      pixels: pixels,
      timestamp: System.system_time(:millisecond),
      id: generate_id(),
      metadata: metadata
    }
  end

  @doc """
  Adds or updates metadata in a frame
  """
  def put_metadata(frame, key, value) do
    new_metadata = Map.put(frame.metadata || %{}, key, value)
    %{frame | metadata: new_metadata}
  end

  @doc """
  Adds a flag in metadata indicating this frame contains parameter changes
  """
  def mark_parameter_change(frame, is_significant \\ false) do
    frame
    |> put_metadata("param_change", true)
    |> put_metadata("significant_change", is_significant)
  end

  # Generate a unique ID for the frame
  defp generate_id do
    :crypto.strong_rand_bytes(8) |> Base.encode16(case: :lower)
  end
end
